#!/bin/bash
if [ -z "$1" ]; then
  echo usage: $0 jvmName
  exit
 fi
java -ea -cp "jars/*:bin" -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     cvm.distributed.CVM$1 jvm$1 config.xml
